name: brain_training
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.0.3 <4.0.0"
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    responsive_builder: ^0.1.4
    provider: ^6.0.2
    logger: ^0.7.0+2
    get_it: ^7.6.0
    get: ^4.6.1
    audio_helper: ^0.0.2    
    flutter_screenutil: ^5.3.1    
    better_sound_effect: ^0.0.3
    equatable: ^1.0.1
    flutter_svg: ^1.0.3    
    lottie: ^1.4.3
    timer_count_down: ^2.2.2
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
flutter:
    uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
    assets:
    - assets/images/
    - assets/sounds/
    - assets/sounds/background/
    - assets/lottie_files/ 
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
    fonts:
        - family: ComicHelvetic
          fonts:
            - asset: assets/fonts/ComicHelvetic_Heavy.otf
            - asset: assets/fonts/ComicHelvetic_Light.otf
            - asset: assets/fonts/ComicHelvetic_Medium.otf
              style: italic
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages